# Generated by Django 5.1.3 on 2024-11-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0002_fileupload_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='file_type',
        ),
    ]
